language: node_js
node_js:
  - '10'

cache:
  directories:
    - '$HOME/.npm'

before_install:
  - npm install -g npm@6.4

install:
  - make install-ci

script:
  - make lint
  - make test
  - make build
  - make package

after_success:
  - make clean

deploy:
  provider: script
  script: make publish-amo
  skip_cleanup: true
  on:
    tags: true
    branch: master
