language: node_js
node_js:
  - "8"

env:
 - MOZILLA_EXTENSION_ID=b4bbcd8e-acc0-4044-b09b-1c15d0b66875

install:
 - make install

script:
 - make lint
 - make test
 - make build
 - make package

after_success:
 - make clean
 - make build-production

deploy:
  provider: script
  script: make publish
  keep_files: true
  on:
    tags: true
    branch: master
