language: node_js
node_js:
  - "8"

install:
 - make install

script:
 - make lint
 - make test
 - make build
 - make package

after_success:
 - make clean

deploy:
  provider: script
  script: make publish-amo
  keep_files: true
  on:
    tags: true
    branch: master
