language: node_js
node_js:
  - "8"

install:
 - make install

script:
 - make lint
 - make test
 - make build
 - make package

deploy:
  provider: script
  script: make publish
  on:
    tags: true
    branch: master
